resources: ["http://vishub.org/excursions/1597","http://vishub.org/excursions/1389"]
owner_email: "virtual.science.hub+1@gmail.com"
additional_tags: ["engineering"]
mediaconversion: false
allowed_domains: ["vishub.org"]
allowed_code_domains: ["vishubcode.org"]
# category_id: 237